### ISSUE TITLE
v1.4.1 and beyond require a package.json in the cwd

### ISSUE THREAD

**Issue by Arcanemagus** [rossPatton/stylint#326]
As discussed over [here](https://github.com/AtomLinter/linter-stylint/issues/27), v1.4.1 and beyond _require_ a `package.json` file in the current working directory due to [this line](https://github.com/rossPatton/stylint/blob/736cdf4feef2b4e565d6b6b5eba62ec1191bf75a/index.js#L31).

This causes problems if `stylint` is being run in a directory that doesn't contain a `package.json`.

**Comment by SimenB** [comment]
Should be fixed https://github.com/rossPatton/stylint/commit/37c2bf8cdd7776710a60e45a36d199e5e8fd1d99

**Comment by rossPatton** [comment]
my bad everyone. this is why you don't code at 4am

**Comment by Arcanemagus** [comment]
Cool, looks like the CI builds over there are still failing so I'll see where the problem is now 😛, thanks!
